language: ruby
rvm:
  - ruby-2.1.9
  - ruby-2.2.5
  - ruby-2.3.1
  - ruby-head
  - rubinius-3.62
  - jruby-9.1.5.0
  - jruby-head
branches:
  only:
    - master
before_install:
  - git submodule update --init --recursive
  - gem install ffi
before_script:
  - rake compile
sudo: false
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
