language: ruby
rvm:
  - "2.1"
  - "2.2"
  - ruby-head
  - rbx-2
  - rbx
  - jruby-head
branches:
  only:
    - master
before_install:
  - git submodule update --init --recursive
  - gem install ffi
before_script:
  - rake compile
sudo: false
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx
