language: ruby
rvm:
  - ruby-2.3.3
  - ruby-2.4.1
  - ruby-head
  - rubinius-3.72
  - jruby-9.1.8.0
  - jruby-head
branches:
  only:
    - master
before_install:
  - git submodule update --init --recursive
  - gem install ffi
before_script:
  - rake compile
sudo: false
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
sudo: required
dist: trusty
