language: ruby
rvm:
  - ruby-2.3.5
  - ruby-2.4.2
  - ruby-head
  - rubinius-3.86
  - rubinius
  - jruby-9.1.13.0
  - jruby-head
branches:
  only:
    - master
before_install:
  - git submodule update --init --recursive
  - gem install ffi
before_script:
  - rake compile
sudo: false
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rubinius
sudo: required
dist: trusty
