language: ruby
rvm:
  - 1.9.2
  - 1.9.3
branches:
  only:
    - master
before_install:
  - sudo apt-get install subversion
  - git submodule update --init --recursive
  - echo "yes" | gem uninstall ffi -a
before_script:
  - rake libuv
