language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - ruby-head
  - rbx
  - jruby-19mode
branches:
  only:
    - master
before_install:
  - sudo apt-get install subversion
  - git submodule update --init --recursive
  - gem install ffi
before_script:
  - rake compile
